debug: false #true일 시, 해당 플러그인이 하는 작업을 버킷 메세지에 출력합니다.

temp-storage-name: "임시 보관함" #임시 보관함의 이름입니다.
temp-storage-message: "보관함에 새 아이템이 있습니다!" #보관함에 아이템이 있을 경우 매 분마다 해당 메세지를 전송합니다.
time-limit: " &6&l[!] &f시간 제한: %t분"

default-game-mode: survival #관전자 상태에서 해제될 때, 기본이 되는 게임모드입니다.
change-game-mode: true #유저가 접속할 시 위의 게임모드로 변경할 지 여부입니다.
auto-save-time: 300 #유저가 접속한 이후로 변수 데이터를 세이브하는 주기입니다. 초 단위입니다.

default-dialog-reader: BOOK #기본 Dialog 출력 아이콘입니다.
default-typing-sound: block.stone_button.click_on 0.2 0.7 #아무것도 설정하지 않았을 시의 타이핑 사운드입니다.
quest-complete-sound: ui.toast.challenge_complete 1 1
default-dialog-rows: 5 #기본 Dialog 줄 길이입니다.
default-dialog-center: 22
default-typing-delay: 2 #Dialog 에서 글자 하나가 넘어가는 속도입니다. 틱 단위입니다.

default-quest-icon: BOOK #퀘스트 GUI 에서 기본이 되는 아이콘 타입입니다.
default-quest-durability: 0

enable-tagging: false #출력하는 아이템에 NBT태그를 붙일지 여부입니다.
enable-skip: true #스킵 기능을 활성화할지 여부입니다.